apiVersion: v2
name: unifi-network-application
description: A Helm Chart for deploying a UniFi controller to Kubernetes
type: application
version: 1.0.0
keywords:
  - unifi
  - controller
  - ubiquiti
home: https://github.com/katallaxie/helm-charts/tree/main/charts/unifi-controller
appVersion: "8.0.7-ls18"
maintainers:
  - name: Sebastian Doell
    email: sebastian@katallaxie.dev
annotations:
  artifacthub.io/changes: |
    - UniFi Controller v8.0.7-ls18
  artifacthub.io/images: |
    - name: unifi-controller
      image: linuxserver/docker-unifi-network-application:8.0.7-ls18
      platforms:
        - linux/amd64
        - linux/arm64
